In [1]:
import numpy as np
import matplotlib.pylab as plt
from numpy import random

In [3]:
# Introduction

list_1 = [1,2,3,4,5]
np_arr_1 = np.array(list_1, dtype=np.int8)
np_arr_1

m_list_1 = [[1,2,3], [4,5,6], [7,8,9]]
np_m_arr_1 = np.array(m_list_1)

In [15]:
np.arange(0, 5, 2)
np.linspace(0, 5, 5)

np.zeros(4)
np.ones((2,3))

# check for the size & dtype
np_m_arr_1.size
np_m_arr_1.dtype

# create random np arrays
np.random.randint(10,50,size=(2,3))

# run this for more info np.random.randint?

array([[21, 27, 49],
       [43, 43, 35]])

In [27]:
# Slicing and Indexes
np_m_arr_1.shape
np_m_arr_1.itemset((1,0), 5)
np_m_arr_1

print(f"np_m_arr_1 \n {np_m_arr_1}")

np.take(np_m_arr_1, [0, 3, 6])
np.put(np_m_arr_1, [0, 3, 6], [10,10,10])

print(f"np_m_arr_1 \n {np_m_arr_1}")

np_m_arr_1[:, 1]
np_m_arr_1[::-1] # flipping the array

evens = np_m_arr_1[np_m_arr_1%2==0] # use logical operators
evens

np_m_arr_1[(np_m_arr_1 > 5) & (np_m_arr_1< 9)] # multiple logical operators

np.unique(np_m_arr_1)

np_m_arr_1 
 [[10  2  3]
 [ 5  5  6]
 [10  8  9]]
np_m_arr_1 
 [[10  2  3]
 [10  5  6]
 [10  8  9]]


array([ 2,  3,  5,  6,  8,  9, 10])

In [41]:
# Reshaping Arrays
print(np_m_arr_1)

np_m_arr_1.reshape((1,9))

np_m_arr_1.transpose() #np_m_arr_1.swapaxes(0,1)
np_m_arr_1.flatten('F') # flatten by column
np_m_arr_1.sort(axis=0)
np_m_arr_1

[[ 2  3 10]
 [ 5  6 10]
 [ 8  9 10]]


array([[ 2,  3, 10],
       [ 5,  6, 10],
       [ 8,  9, 10]])

In [46]:
# Stacking & Splitting
ss_arr_1 = np.random.randint(10, size=(2,2))
print(f"ss\n {ss_arr_1}")

ss_arr_3 = np.delete(ss_arr_1, 1, 0)
ss_arr_3

ss
 [[0 7]
 [6 1]]


array([[0, 7]])